#!/usr/bin/env bash
set -ex

short=$1
src=$2

if [ "$CI" = "" ]
then
   echo "Not on Circle, using parallel compilation."
   cmd=rparmake
   branch=`git rev-parse --abbrev-ref HEAD`
else
   echo "On Circle, not using parallel compilation to avoid running out of memory."
   cmd=rmake
   branch=${CIRCLE_BRANCH}
fi

dist=duckuments-dist

mkdir -p ${dist}

DISABLE_CONTRACTS=1 mcdp-render-manual \
    --src ${src} \
    --resources docs:${dist} \
    --stylesheet v_manual_split \
    --symbols docs/symbols.tex \
    -o out/${short} \
    --permalink_prefix http://docs.duckietown.org/branch/${branch}/${short}/out/link.html \
    --split       ${dist}/${short}/out/ \
    --pdf         ${dist}/${short}/out.pdf \
    --output_file ${dist}/${short}/out.html \
    -c "config echo 1; ${cmd}"
