#!/usr/bin/env bash
set -e

short=$1
src=$2

echo CI=$CI

if [ "$CI" = "" ]
then
   echo "Not on Circle, using rparmake"
   cmd=rparmake
else
   echo "On Circle, using rmake"
   cmd=rmake
fi

dist=duckuments-dist

mkdir -p ${dist}

DISABLE_CONTRACTS=1 mcdp-render-manual \
    --src ${src} \
    --resources docs:${dist} \
    --stylesheet v_manual_split \
    --symbols docs/symbols.tex \
    -o out/${short} \
    --permalink_prefix http://purl.org/dt/${short}/ \
    --split       ${dist}/${short}/${short}/ \
    --pdf         ${dist}/${short}/${short}.pdf \
    --output_file ${dist}/${short}/${short}.html \
    -c "config echo 1; ${cmd}"
