version: 2
jobs:
    build:
        docker:
        - image: andreacensi/duckietown-xenial-kinetic:19
          environment:
              COLUMNS: 160
              NODE_PATH: /root/project/node_modules
              MPLBACKEND: agg

        resource_class: large

        steps:
        - checkout
        - run:
            name: NPM
            command: |
                curl -sL https://deb.nodesource.com/setup_6.x | bash
                apt install -y nodejs
                npm install MathJax-node jsdom@9.3 less

        - run:
            name: setup MCDP
            command: |
                git submodule sync --recursive
                git submodule update --init --recursive
                pip install -r mcdp/requirements.txt
                cd mcdp && python setup.py develop

        - run:
            name: Check Programs
            command: |
                apt install -y node-less
                make check-programs

        - run:
            name: checkout duckietown repository
            command: |
                git clone -b master --depth 1 git@github.com:duckietown/Software /tmp/git_repos/duckietown/Software/master
                ln -s /tmp/git_repos/duckietown/Software/master/ duckietown

        - run:
            name: Compile all books
            command: |
                echo "config colorize 0" > .compmake.rc
                # 2 cpus
                make -j4 books

        - run:
            name: Compile all books again to get cross references again
            command: |
                make -j4 books

        - store_artifacts:
              path: duckuments-dist
              destination: duckuments-dist

        - run:
            name: Package artifacts
            command:  |
                bash package-art.sh out/package.tgz
#
#        - run:
#            name: Collecting job failure results
#            when: always
#            command: |
#                mkdir -p out/comptests/junit
#                comptests-to-junit out/comptests/compmake >  out/comptests/junit/junit.xml
#
#        - test-results-store:
#            path: out/comptests/junit

        - store_artifacts:
              path: out/package.tgz
              destination: out/package.tgz
